language: java

jdk: openjdk8

script:
  - echo "Hola Travis"
  - mvn package
  - ssh-heyscan -H ec2-3-134-28-16.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
  - scp -i "acceso_instancia.pem" *.war ubuntu@ec2-3-134-28-16.us-east-2.compute.amazonaws.com:/tmp
