language: java

jdk: openjdk8

script:
  - echo "Hola Travis"
  - mvn package
  - chmod 400 "acceso_instancia.pem"
  - ssh-keyscan -H 3.134.28.16 >> ~/.ssh/known_hosts
  - ssh-keyscan -H ec2-3-134-28-16.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
  - ssh -i acceso_instancia.pem ubuntu@3.134.28.16 "rm -rf /var/lib/tomcat8/webapps/Netflix*"
  - ls -la target
  - scp -i "acceso_instancia.pem" target/*.war ubuntu@ec2-3-134-28-16.us-east-2.compute.amazonaws.com:/var/lib/tomcat8/webapps/Netflix.war
